import Head from "next/head";
import Aboutme from "@/components/Aboutme";
import Banner from "@/components/Banner";
import Project from "@/components/Project";
import Contact from "@/components/Contact";
import ScrollArrow from "@/components/shared/ScrollArrow";
import Footer from "@/components/Footer";

// export const getStaticProps = async () => {
//   const homes: PageData.IndexPageData = await getHomePageData();
//   return {
//     props: { homes }
//   };
// };

export default function Home() {
  return (
    <>
      <Head>
        <title>Nilima Bhujel</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <section className="container m-auto">
          <Banner />
          <section id="about-me">
            <h1 className="text-[50px] mb-8 font-semibold">About Me</h1>
            <Aboutme />
          </section>
          <section className="md:mt-4" id="recent-project">
            <h1 className="text-[50px] mb-8 font-semibold">Recent Work</h1>
            <Project />
          </section>
          <section className="mt-12" id="contact">
            <Contact />
            <ScrollArrow/>
          </section>
          <Footer/>
        </section>
      </main>
    </>
  );
}
