import Head from "next/head";
import Aboutme from "@/components/Aboutme";
import Banner from "@/components/Banner";
import Project from "@/components/Project";
import Contact from "@/components/Contact";
import ScrollArrow from "@/components/shared/ScrollArrow";
import Footer from "@/components/Footer";
import { PageData } from "@/types/data";
import { getHomePageData } from "@/service/homepage";

export const getStaticProps = async () => {
  const pages: PageData.Data = await getHomePageData();
  return {
    props: { pages },
  };
};

export default function Home({ pages }: PageData.Data) {
  console.log(pages);
  return (
    <>
      <Head>
        <title>Nilima Bhujel</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <section className="container m-auto">
          <Banner pages={pages}/>
          <section id="about-me">
            <h1 className="text-[50px] mb-8 font-semibold">{pages[0].about.title}</h1>
            <Aboutme pages={pages}/>
          </section>
          <section className="md:mt-4" id="recent-project">
            <h1 className="text-[50px] mb-8 font-semibold">{pages[0].project.title}</h1>
            <Project pages={pages}/>
          </section>
          <section className="mt-12" id="contact">
            <Contact />
            <ScrollArrow />
          </section>
          <Footer />
        </section>
      </main>
    </>
  );
}
